version: "3.8"

services:
  api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:latest
    restart: always
    depends_on:
      - redis
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
      - traefik-net
    env_file:
      - .env
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.evolution-api.entrypoints=websecure"
      - "traefik.http.routers.evolution-api.rule=Host(`evo.bodogami.tech`)"
      - "traefik.http.routers.evolution-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.evolution-api.loadbalancer.server.port=8080"

  frontend:
    container_name: evolution_frontend
    image: evoapicloud/evolution-manager:latest
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./Docker/evolution-manager/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    networks:
      - evolution-net

  redis:
    container_name: evolution_redis
    image: redis:latest
    restart: always
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    networks:
      evolution-net:
        aliases:
          - evolution-redis
      traefik-net:
        aliases:
          - evolution-redis
    expose:
      - "6379"

volumes:
  evolution_instances:
  evolution_redis:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge
  traefik-net:
    name: infra_default
    external: true